### ISSUE TITLE
Starting fails: Operation not permitted

### ISSUE THREAD

**Issue by caffeineshock** [babim/docker-sandstorm#1]
Starting the container fails after pulling the latest version from the hub with the following error:

```
*** Uncaught exception ***
sandstorm/run-bundle.c++:1039: failed: unshare(CLONE_NEWUSER): Operation not permitted
stack: 0x50a7f7 0x50a719 0x50a70a 0x4a995f 0x4a947a
```

Im running on Ubuntu 16.04 with Docker version 1.11.0, build 4dc5990.

**Comment by babim** [comment]
sorry about reply late.
This time I can't check. I will check and reply soon. But sandstorm need a module active from kernel, I can't remmember.

**Comment by babim** [comment]
@caffeineshock I'm sorry. I forget reply to u. I can't use this build too.
Sandstorm can't run on docker, but if you want create a minimal VM to run sandstorm, you can use rancheros. I tested and work with minimal resource.
